### ISSUE TITLE
sudo docker compose exec web python manage.py create_db keeps returning an error message

### ISSUE THREAD

**Issue by Behordeun** [HealthIQ-LLC/master-patient-index#1]
Attaching to master-patient-index-db-1, master-patient-index-web-1
master-patient-index-web-1  | Waiting for postgres...
master-patient-index-web-1  | PostgreSQL started
master-patient-index-web-1  | Usage: manage.py create_db [OPTIONS]
master-patient-index-web-1  | Try 'manage.py create_db --help' for help.
master-patient-index-web-1  | 
master-patient-index-web-1  | Error: Could not import 'project.init'.
master-patient-index-web-1  | Usage: manage.py run [OPTIONS]
master-patient-index-web-1  | Try 'manage.py run --help' for help.
master-patient-index-web-1  | 
master-patient-index-web-1  | Error: Could not import 'project.init'.
master-patient-index-web-1 exited with code 2

<img width="1440" alt="image" src="https://github.com/HealthIQ-LLC/master-patient-index/assets/45925374/56bba689-afc1-464b-b10a-97e60795d7b3">

How can I fix this, please?

**Comment by jreznick** [comment]
Hi, Behordeun. When I run the command you do, I do not successfully reproduce this error. Note around half way through the line:

"Serving Flask app 'project/__init__.py"

That is the module noted in your error. What working directory are you in when you run the command
`sudo docker compose - docker-compose.dev.yml up`? And do you have some kind of virtualenv running on your system?


![image](https://github.com/HealthIQ-LLC/master-patient-index/assets/4438696/cb411d50-fbaa-4cf8-8fb2-4e003dec6b9f)

**Comment by jreznick** [comment]
Also did you try `sudo docker compose - docker-compose.dev.yml up build` (sudo only if necessary on your host) or just without `build` in the command?

**Comment by Behordeun** [comment]
I was in the base directory of the project.

I couldn't find any **init**.py in the the **services/web/project** directory

> Hi, Behordeun. When I run the command you do, I do not successfully reproduce this error. Note around half way through the line:
> 
> "Serving Flask app 'project/**init**.py"
> 
> That is the module noted in your error. What working directory are you in when you run the command `sudo docker compose - docker-compose.dev.yml up`? And do you have some kind of virtualenv running on your system?
> 
> ![image](https://user-images.githubusercontent.com/4438696/275355659-cb411d50-fbaa-4cf8-8fb2-4e003dec6b9f.png)

**Comment by jreznick** [comment]
It's `__init__` or https://github.com/HealthIQ-LLC/master-patient-index/blob/main/services/web/project/__init__.py

So I'm a little confused by this error to be honest. When you say base directory, you mean you're in `master-patient-index` where the docker-compose files reside, and that's correct, and you have `docker` and `flask` installed already? Do you have some kind of virtualenv running? I want to be able to reproduce your error or walk you through it, of course!

Have you tried the `build` command so it's `sudo docker compose - docker-compose.dev.yml up build`? 

Alternatively, have you tried the `prod` build and `prod` container? I'd like to see if you experience the same thing.

**Comment by jreznick** [comment]
Behordeun, you have helped me discover a flaw in the documentation when it was converted to markdown. In the code secrets files `.env.dev` and `.env.prod` the first line appears in the documentation as

`FLASK_APP=project/init.py` but the module needs to be `__init__.py` (double underscores  '__' around init). I did not escape the dunders in markdown correctly, and will be fixing the docs accordingly with my next release!

**Comment by Behordeun** [comment]
Thanks, @jreznick, for taking the time to guide me through the setup. I am looking forward to contributing to the project and, most importantly, its launch.
